(async()=>{'use strict';
const b64=window.SIMULEX_DATA_PARTS.join('');const bin=atob(b64);const gz=Uint8Array.from(bin,c=>c.charCodeAt(0));const DATA=JSON.parse(await new Response(new Blob([gz]).stream().pipeThrough(new DecompressionStream('gzip'))).text());
window.DATA=DATA; window.SIMULEX_ASSET_BUNDLES={}; window.SIMULEX_ASSET_BASE=window.SIMULEX_ASSET_BASE||'assets/';
const KEY='simulex_academy_ar_v2'; let P=JSON.parse(localStorage.getItem(KEY)||'{"answers":{},"progress":{},"drafts":{}}');
let nav={view:'home',skill:null,part:null,model:null}, session=null;
const main=document.getElementById('main');
const sec={Leseverstehen:['Leseverstehen','فهم المقروء'],Sprachbausteine:['Sprachbausteine','القواعد والمفردات'],Hörverstehen:['Hörverstehen','فهم المسموع'],'Schriftlicher Ausdruck':['Schreiben','الكتابة']};
function save(){localStorage.setItem(KEY,JSON.stringify(P));}
function e(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function title(de,ar){return `<h1 class="title" lang="de">${de}</h1><p class="lead">${ar}</p>`}
function crumbs(q){return `<div class="crumbs"><b lang="de">${e(q.section)}</b><span>←</span><b lang="de">${e(q.part||'Aufgabe')}</b><span>←</span><b lang="de">${e(q.model_id)}</b><span>←</span><span>${e(q.question_number)}</span></div>`}
window.menu=()=>document.getElementById('side').classList.toggle('open');
window.go=v=>{nav.view=v;document.getElementById('side').classList.remove('open');render()};
function stats(){let a=Object.values(P.answers);return {answered:a.length,correct:a.filter(x=>x.correct).length,acc:a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):0}}
function render(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.v===nav.view)); if(nav.view==='home')home();else if(nav.view==='path')path();else if(nav.view==='models')models();else if(nav.view==='quality')quality();else if(nav.view==='weak')weak();else home();}
function home(){let s=stats();main.innerHTML=title('SimuLex Academy B1','أكاديمية تفاعلية تبدأ بالشرح، ثم التدريب الموجّه، ثم التقييم.')+`<div class="grid"><div class="card"><div class="metric">${DATA.questions.length}</div><p>سؤالاً ومهمة محفوظة دون حذف</p></div><div class="card"><div class="metric">${DATA.models.length}</div><p>نموذجاً مصدرياً</p></div><div class="card"><div class="metric">${s.answered}</div><p>إجابة مسجلة</p></div><div class="card"><div class="metric">${s.acc}%</div><p>دقة الإجابات المؤهلة</p></div></div><div class="card" style="margin-top:14px"><h2>ابدأ بالتدرج</h2><p>اختر المهارة، ثم الجزء، ثم النموذج. قبل كل مجموعة ستظهر استراتيجية الحل بالعربية، بينما يبقى محتوى الامتحان بالألمانية.</p><button class="btn" onclick="go('path')">فتح مسار التعلّم</button></div><div class="notice"><b>سياسة الجودة:</b> الأسئلة ذات المفاتيح الفارغة أو المحتاجة للمراجعة لا تظهر في وضع الامتحان المقيم، لكنها تبقى محفوظة في قاعدة الجودة ولا تُحذف.</div>`}
function path(){main.innerHTML=title('Lernpfad','مسار التعلّم الهرمي: المهارة ← الجزء ← النموذج ← الأسئلة.')+`<div class="grid">${Object.entries(sec).map(([k,v])=>{let n=DATA.questions.filter(q=>q.section===k).length;return `<div class="card"><h2 lang="de">${v[0]}</h2><p>${v[1]}</p><div class="metric">${n}</div><button class="btn" onclick="chooseSkill('${k}')">اختيار المهارة</button></div>`}).join('')}</div>`}
window.chooseSkill=k=>{nav.skill=k;let parts=[...new Set(DATA.questions.filter(q=>q.section===k).map(q=>q.part||'Aufgabe'))];main.innerHTML=title(sec[k][0],sec[k][1])+`<div class="grid">${parts.map(p=>{let n=DATA.questions.filter(q=>q.section===k&&(q.part||'Aufgabe')===p).length;return `<div class="card"><h2 lang="de">${e(p)}</h2><p>${n} سؤالاً</p><button class="btn" onclick="choosePart('${e(p)}')">اختيار الجزء</button></div>`}).join('')}</div>`}
window.choosePart=p=>{nav.part=p;let mids=[...new Set(DATA.questions.filter(q=>q.section===nav.skill&&(q.part||'Aufgabe')===p).map(q=>q.model_id))];main.innerHTML=title(p,'اختر النموذج داخل هذا الجزء.')+`<div class="model-list">${mids.map(mid=>{let m=DATA.models.find(x=>x.model_id===mid),arr=DATA.questions.filter(q=>q.model_id===mid&&q.section===nav.skill&&(q.part||'Aufgabe')===p),eligible=arr.filter(q=>q.exam_eligible).length;return `<div class="model"><h3 lang="de">${e(m?.title_de||mid)}</h3><p>${arr.length} سؤالاً · ${eligible} مؤهلاً للتقييم</p><button class="btn" onclick="startSet('${mid}')">بدء التعليم والتدريب</button></div>`}).join('')}</div>`}
window.startSet=mid=>{let list=DATA.questions.filter(q=>q.model_id===mid&&q.section===nav.skill&&(q.part||'Aufgabe')===nav.part);session={list,index:0,score:0,answered:0,locked:false};showQ()}
function showQ(){if(!session||session.index>=session.list.length){result();return}let q=session.list[session.index],opts=q.options||[];let input='';if(q.question_type==='writing_prompt')input=`<textarea id="draft" style="width:100%;min-height:180px" oninput="saveDraft('${q.id}',this.value)">${e(P.drafts[q.id]||'')}</textarea>`;else if(opts.length)input=`<div class="options">${opts.map(o=>`<button class="option" onclick="answer('${e(String(o))}')">${e(o)}</button>`).join('')}</div>`;else input=`<div class="notice">هذا السؤال يعتمد على بنك عناوين أو صورة مصدرية. افتح المصدر ثم اختر من الأزرار التي ينشئها النموذج عند توفر البنك.</div>${headingButtons(q)}`;main.innerHTML=crumbs(q)+`<div class="teach"><b>الشرح قبل السؤال</b><br>${e(q.learning_intro_ar)}</div><div class="question"><div class="german" lang="de">${e(q.instruction)}\n\n${e(q.context_text||'')}\n\n${e(q.prompt_text)}</div>${input}<div id="feedback"></div>${sourceBox(q)}</div><div class="actions"><button class="btn alt" onclick="prevQ()">السابق</button><button class="btn" onclick="nextQ()">التالي</button></div>`}
function headingButtons(q){let m=DATA.models.find(x=>x.model_id===q.model_id),bank=m?.heading_bank||[];return bank.length?`<div class="options">${bank.map((x,i)=>`<button class="option" onclick="answer('${String.fromCharCode(65+i)}')">${String.fromCharCode(65+i)} — ${e(x)}</button>`).join('')}</div>`:''}
window.answer=a=>{if(session.locked)return;let q=session.list[session.index];session.locked=true;let scored=q.exam_eligible,correct=scored&&String(a).toLowerCase()===String(q.answer).toLowerCase();if(scored){session.answered++;if(correct)session.score++;P.answers[q.id]={correct,answer:a,skill:q.skill,part:q.part,model:q.model_id};save()}document.querySelectorAll('.option').forEach(b=>{b.disabled=true;let t=b.textContent.trim().split('—')[0].trim();if(String(t).toLowerCase()===String(q.answer).toLowerCase())b.classList.add('correct');else if(String(t).toLowerCase()===String(a).toLowerCase())b.classList.add('wrong')});document.getElementById('feedback').innerHTML=`<div class="teach"><b>${scored?(correct?'إجابة صحيحة':'تعلّم من الخطأ'):'سؤال غير مقيم'}</b><br>${e(q.explanation_ar)}${!q.exam_eligible?`<br><b>سبب العزل:</b> ${e(q.exclusion_reason_ar)}`:''}</div>`}
window.nextQ=()=>{session.index++;session.locked=false;showQ()}; window.prevQ=()=>{if(session.index>0)session.index--;session.locked=false;showQ()};
window.saveDraft=(id,v)=>{P.drafts[id]=v;save()};
function result(){let pct=session.answered?Math.round(session.score/session.answered*100):0;main.innerHTML=title('Auswertung','نتيجة المجموعة التعليمية.')+`<div class="card"><div class="metric">${pct}%</div><p>${session.score} إجابة صحيحة من ${session.answered} سؤالاً مؤهلاً للتقييم.</p><button class="btn" onclick="go('weak')">مراجعة نقاط الضعف</button></div>`}
function sourceBox(q){let role=q.image_key?.split(':')[1]||'',m=DATA.models.find(x=>x.model_id===q.model_id),has=role&&m?.asset_roles?.[role];return `<div class="source"><button class="btn alt" onclick="loadSource('${q.model_id}','${role}','src_${q.id}')">إظهار صورة المصدر</button><div id="src_${q.id}">${has?'':'<small>لا توجد صورة مرتبطة مباشرة بهذا السؤال.</small>'}</div></div>`}
window.loadSource=async(mid,role,id)=>{let box=document.getElementById(id);if(!role){box.innerHTML='<small>لا توجد صورة مرتبطة.</small>';return}if(!window.SIMULEX_ASSET_BUNDLES[mid]){try{await new Promise((ok,no)=>{let s=document.createElement('script');s.src=`${window.SIMULEX_ASSET_BASE}${mid}.js`;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}catch(err){box.innerHTML='<small>صورة المصدر متاحة داخل حزمة الأوفلاين الكاملة، وليست مرفوعة في النسخة الخفيفة.</small>';return}}let item=window.SIMULEX_ASSET_BUNDLES[mid]?.[role];if(!item){box.innerHTML='<small>الصورة غير متوفرة.</small>';return}let bytes=Uint8Array.from(atob(item.b64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:item.mime}));box.innerHTML=`<img loading="lazy" src="${url}" alt="German source page">`}
function models(){main.innerHTML=title('Modellprüfungen','النماذج الكاملة. وضع الامتحان يستبعد تلقائياً الأسئلة غير الموثقة.')+`<div class="model-list">${DATA.models.map(m=>{let all=DATA.questions.filter(q=>q.model_id===m.model_id),ok=all.filter(q=>q.exam_eligible);return `<div class="model"><h3 lang="de">${e(m.title_de||m.model_id)}</h3><p>${all.length} محفوظ · ${ok.length} مقيم</p><button class="btn" onclick="exam('${m.model_id}')">بدء الامتحان الموثق</button></div>`}).join('')}</div>`}
window.exam=mid=>{session={list:DATA.questions.filter(q=>q.model_id===mid&&q.exam_eligible),index:0,score:0,answered:0,locked:false};showQ()}
function quality(){let empty=DATA.questions.filter(q=>!q.answer).length,rev=DATA.questions.filter(q=>q.needs_review).length,expl=DATA.questions.filter(q=>q.explanation_ar).length;main.innerHTML=title('Qualität und Quellen','لوحة الجودة والمصادر.')+`<div class="grid"><div class="card"><div class="metric">${empty}</div><p>مفتاحاً فارغاً ومعزولاً</p></div><div class="card"><div class="metric">${rev}</div><p>سؤالاً يحتاج مراجعة</p></div><div class="card"><div class="metric">${expl}</div><p>شرحاً تعليمياً عربياً</p></div></div><div class="notice">لا تُرفع علامة المراجعة تلقائياً. أي سؤال غير مؤكد يظل موجوداً للشفافية، لكنه لا يدخل نتيجة الامتحان.</div>`}
function weak(){let rows={};Object.values(P.answers).forEach(a=>{let k=(a.skill||'other')+'|'+(a.part||'');rows[k]=rows[k]||{n:0,w:0};rows[k].n++;if(!a.correct)rows[k].w++});let arr=Object.entries(rows).sort((a,b)=>(b[1].w/b[1].n)-(a[1].w/a[1].n));main.innerHTML=title('Fehleranalyse','تحليل الأخطاء حسب المهارة والجزء.')+(arr.length?`<table class="table"><tr><th>المهارة والجزء</th><th>المحاولات</th><th>معدل الخطأ</th></tr>${arr.map(([k,v])=>`<tr><td lang="de">${e(k)}</td><td>${v.n}</td><td>${Math.round(v.w/v.n*100)}%</td></tr>`).join('')}</table>`:'<div class="notice">ابدأ التدريب أولاً ليظهر تحليل الضعف.</div>')}
window.exportData=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(P,null,2)],{type:'application/json'}));a.download='simulex-progress.json';a.click()};
window.importData=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{P=JSON.parse(r.result);save();render()};r.readAsText(f)};
window.prepareDeploy=()=>{try{const html='<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SimuLex Academy B1</title><link rel="stylesheet" href="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/styles.css"><script src="https://cdn.jsdelivr.net/npm/lz-string@1.5.0/libs/lz-string.min.js"></script></head><body><header class="top"><div><div class="brand" lang="de">SimuLex Academy B1</div><div class="sub">محتوى ألماني · تعليم وإرشاد عربي</div></div></header><div class="layout"><aside class="side" id="side"><div class="nav-title">التعلّم</div><button class="nav" data-v="home" onclick="go(\'home\')"><span lang="de">Startseite</span><small>الصفحة الرئيسية</small></button><button class="nav" data-v="path" onclick="go(\'path\')"><span lang="de">Lernpfad</span><small>مسار التعلّم</small></button><button class="nav" data-v="models" onclick="go(\'models\')"><span lang="de">Modellprüfungen</span><small>النماذج الكاملة</small></button><button class="nav" data-v="weak" onclick="go(\'weak\')"><span lang="de">Fehleranalyse</span><small>تحليل الأخطاء</small></button><button class="nav" data-v="quality" onclick="go(\'quality\')"><span lang="de">Qualität und Quellen</span><small>الجودة والمصادر</small></button></aside><main id="main" class="main"></main></div><script>window.SIMULEX_ASSET_BASE="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/assets/";window.SIMULEX_DATA_PARTS=[];</script><script src="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/data/p00.js"></script><script src="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/data/p01.js"></script><script src="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/data/p02.js"></script><script src="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/data/p03.js"></script><script src="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/data/p04.js"></script><script src="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/data/p05.js"></script><script src="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/data/p06.js"></script><script src="https://raw.githubusercontent.com/zeethar87-star/psychometrics/main/simulex-b1-academy/app.js"></script></body></html>';let files={'index.html':{content:html},'sandbox.config.json':{content:'{"template":"static"}'}};let b=LZString.compressToBase64(JSON.stringify({files})).replace(/\+/g,'-').replace(/\//g,'_');document.getElementById('deployParameters').value=b;return true}catch(x){alert('تعذر تجهيز النشر السحابي.');return false}};
render();
})();